name: CI/CD for Strapi
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.HARIPRIYA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.HARIPRIYA_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: Install SSH client
        run: sudo apt-get install openssh-client
      - name: Deploy Strapi Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HARIPRIYA_EC2_HOST }}
          username: ${{ secrets.HARIPRIYA_EC2_USER }}
          key: ${{ secrets.HARIPRIYA_EC2_KEY }}
          script: |
            #set -e
            cd /srv/strapi
            sudo git pull origin main
            sudo chmod +x  generate_env_variables.sh
            sudo ./generate_env_variables.sh
            sudo npm install
            sudo npm run build
            # Check if Strapi is already managed by pm2
            if ! sudo pm2 status | grep -q "strapi-project" ; then
            echo "Strapi is not managed by pm2. Starting Strapi with pm2..."
            sudo pm2 start "npm run start --silent" --name "strapi-project"
            else
            echo "Strapi is already managed by pm2. Restarting Strapi..."
            sudo pm2 restart strapi-project 
            fi
           
          

           
